#ifndef CONSTANTS_H
#define CONSTANTS_H
#include "pinouts.h"


static const int STEERING_PIN = STEERING_MIDDLE;

//*** line sensor mesurements ***//
const int SENSOR_ANGLES[15] = {-30, -20, -15, -10, -5, -3, -1, 0, 1, 3, 5, 10, 15, 20, 30}; //non-symetric line following


//steering servo
const int NOSE_RIGHT_MAX = 55;
const int NOSE_CENTER = 100;
const int NOSE_LEFT_MAX = 145;

static const int NUMBER_OF_PINS = 8;
static const int LINE_SENSOR[NUMBER_OF_PINS] = {LINE_SENSOR_0, LINE_SENSOR_1,LINE_SENSOR_2,
	LINE_SENSOR_3, LINE_SENSOR_4, LINE_SENSOR_5, LINE_SENSOR_6, LINE_SENSOR_7};

const int PWMR = WHEEL_PWM_BR;
const int PWML = WHEEL_PWM_BL;


//wall distances
const int DIST_START_TURN = 380; //we expect for Tails this should be the RS
const int DIST_HARD_TURN = 500; 
const int DIST_END_TURN = 105;
const int WALL_DIST = 600; //R (not RS) 45 deg. out the side. Says how far away from wall to follow

const int SPEED = 200; //Between 0-255
//const int MAX_SPEED = 255;
const int TURN_SPEED = 105; 

enum State {LINE_FOLLOW, LEFT_TURN1, LEFT_TURN_TO_WALL, RIGHT_TURN_TO_WALL, RIGHT_TURN1, RIGHT_TURN2, RIGHT_TURN3,
            OFF_WALL, ON_WALL, WALL_FOLLOW_R, WALL_FOLLOW_L, FOLLOW_TIME_LINE, TO_WALL,
            LINE_FOLLOW_UNTIL_XING, EDGE_AREA, FOLLOW_TILL_SNORKLE, FOLLOW_TIME, FOLLOW_TIME_SHORT, FOLLOW_TIME_STOP,
            WALL_UNTIL_LOSE, GENTLE_RT, GENTLE_RT2, GENTLE_LT, GENTLE_LT_2, GENTLE_LT_3, PRE_PARK, PARK, STOP,
            STRAIGHTtoWALL, RIGHT_TURN_MAX, RIGHT_TURN_MAX_2, BACK_UP, FIND_LINE_BEGIN, STRAIGHT_TIME, STRAIGHT_TIME_SLOW, TIME };

//_NEW
const int stateMap[35] = {
  TIME, FOLLOW_TIME_LINE, TO_WALL,//FIND_LINE_BEGIN, //3 Get to inner circle
  RIGHT_TURN3, FOLLOW_TIME, FOLLOW_TILL_SNORKLE,//6 DROP 1
  RIGHT_TURN_MAX, RIGHT_TURN_MAX_2, RIGHT_TURN_TO_WALL, GENTLE_LT_2, LINE_FOLLOW_UNTIL_XING, RIGHT_TURN1, RIGHT_TURN2, //1 DELIVER 2
  LINE_FOLLOW_UNTIL_XING, STRAIGHT_TIME, FOLLOW_TIME_STOP, LINE_FOLLOW_UNTIL_XING, RIGHT_TURN1, RIGHT_TURN2, //20 DELIVER 3
  LINE_FOLLOW_UNTIL_XING, STRAIGHT_TIME, LINE_FOLLOW, STRAIGHT_TIME, LINE_FOLLOW_UNTIL_XING, RIGHT_TURN1, RIGHT_TURN2, //27 DELIVER 4  
  LINE_FOLLOW_UNTIL_XING, STRAIGHT_TIME, LINE_FOLLOW, RIGHT_TURN1, RIGHT_TURN2, //32 DELIVER 5
  FOLLOW_TIME_SHORT, PRE_PARK, PARK, STOP };

//const bool doWeDrop[15] = { true, false, true, false, true, false, true, false, true, false, true, false, false};


#endif
