#ifndef CONSTANTS_H
#define CONSTANTS_H
#include "pinouts.h"


static const int STEERING_PIN = STEERING_MIDDLE;

//*** line sensor mesurements ***//
const int SENSOR_ANGLES[14] = {-25, -15, -5, -3, -1, 0, 1, 3, 5, 10, 15, 20, 25, 30}; //non-symetric line following


//steering servo
const int NOSE_RIGHT_MAX = 40;
const int NOSE_CENTER = 92;
const int NOSE_LEFT_MAX = 140;

static const int NUMBER_OF_PINS = 8;
static const int LINE_SENSOR[NUMBER_OF_PINS] = {LINE_SENSOR_0, LINE_SENSOR_1,LINE_SENSOR_2,
	LINE_SENSOR_3, LINE_SENSOR_4, LINE_SENSOR_5, LINE_SENSOR_6, LINE_SENSOR_7};

const int PWMR = WHEEL_PWM_BR;
const int PWML = WHEEL_PWM_BL;


//wall distances
const int DIST_START_TURN = 600;
const int DIST_HARD_TURN = 840;
const int DIST_END_TURN = 200;
const int WALL_DIST = 600;

const int SPEED = 210; //Between 0-255
//const int MAX_SPEED = 255;
const int TURN_SPEED = 90; 

enum State {LINE_FOLLOW, LEFT_TURN1, LEFT_TURN2, LEFT_TURN2_2, RIGHT_TURN1, RIGHT_TURN2, RIGHT_TURN3, STRAIGHT_TIME, ON_WALL,
WALL_FOLLOW_R, WALL_FOLLOW_L, MIDDLE_AREA1, MIDDLE_AREA2, LINE_FOLLOW_UNTIL_XING, LINE_FOLLOW_UNTIL_CORNER, EDGE_AREA, FOLLOW_TILL_LOSE,
FOLLOW_TIME, FOLLOW_TIME_SHORT, WALL_UNTIL_LOSE, GENTLE_RT, GENTLE_RT2, GENTLE_LT, GENTLE_LT_2, PRE_PARK,
PARK, STOP, STRAIGHTtoWALL, LEFT_TURN_MAX, BACK_UP, TURN_TO_LINE, BACK_UP_STRAIGHT };

//_NEW
const int stateMap[33] = {
LINE_FOLLOW, LEFT_TURN1,  LEFT_TURN2,//FIRST BOX_2
LINE_FOLLOW, STRAIGHT_TIME, // CROSS THE T-JUNCTION_4
LINE_FOLLOW, LEFT_TURN1,  LEFT_TURN2, //SECOND BOX_7
LINE_FOLLOW, LEFT_TURN1,  LEFT_TURN2,  //THIRD BOX_10
LINE_FOLLOW, GENTLE_RT2, GENTLE_RT, LINE_FOLLOW_UNTIL_CORNER, BACK_UP_STRAIGHT, BACK_UP, TURN_TO_LINE, //U-TURN 16
LINE_FOLLOW, LEFT_TURN1,  LEFT_TURN2_2, //FOURTH BOX 19
LINE_FOLLOW, LEFT_TURN1,  LEFT_TURN2, //FIFTH BOX 22
LINE_FOLLOW, STRAIGHT_TIME, // 25
LINE_FOLLOW, LEFT_TURN1,  LEFT_TURN2, //28
LINE_FOLLOW, FOLLOW_TIME_SHORT, PARK, STOP };

//const bool doWeDrop[15] = { true, false, true, false, true, false, true, false, true, false, true, false, false};


#endif
